import graphviz as graphviz

graph = graphviz.Digraph()
graph.edge('10AM, start','check mails')
graph.edge('check mails','check metrics for pipelines')
graph.edge('check metrics for pipelines','resolve issues',label='If bug found')
graph.edge('resolve issues','11AM, attend scrum')
graph.edge('check metrics for pipelines','11AM, attend scrum')
graph.edge('11AM, attend scrum','work on Jira Ticket assigned')
graph.edge('work on Jira Ticket assigned','EDA',label='usually')
graph.edge('work on Jira Ticket assigned','SQL Queries',label='Almost everyday')
graph.edge('work on Jira Ticket assigned','ML Modeling',label='seldom')
graph.edge('EDA','SQL Queries')
graph.edge('SQL Queries','EDA')
graph.edge('work on Jira Ticket assigned','Some meeting')
graph.edge('work on Jira Ticket assigned','Around 6PM')
graph.edge('Around 6PM','end')
graph.edge('Some meeting','end',label='If too long')
graph.edge('Some meeting','work on Jira Ticket assigned')